# Generated by Django 5.2.7 on 2025-11-02 10:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_add_quiz_access_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='difficulty_score',
            field=models.FloatField(default=1.0, help_text='Difficulty score from 1.0 (easy) to 5.0 (hard)', validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=10),
        ),
    ]
