# Generated by Django 5.2.7 on 2025-11-15 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_question_difficulty_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='difficulty_score',
        ),
    ]
